apiVersion: ENC[AES256_GCM,data:EIc=,iv:akq80P4QOau4fG02DTTkmzeM83dCZpX/7OifqQam4ms=,tag:5jlzlYWyjWTAQdRgV27W4A==,type:str]
kind: ENC[AES256_GCM,data:a0AWwpcz,iv:mBp+3yz+rp9t/mdjfYZ2XRB9cgeqCu2YpCEBgUzEiNI=,tag:9AwPtV9GiIjDYqK0g+cLhQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QgGAePL3KOO3PiBgteAjG+dw5pD2lg8=,iv:TiEMLa0eLWSIRYBFgBeFnroagtC6wmfsrVO2CoAi7BU=,tag:9t2yEA5dlbpgL1EVZU3xSQ==,type:str]
    namespace: ENC[AES256_GCM,data:6wGOZyN3p3OJANI=,iv:AkEzI2eatP+QWQtAp5Xis11bZ/j9mzHgHVrvhTbkN5A=,tag:CYJEsmITJKf9ehDk2BrWew==,type:str]
type: ENC[AES256_GCM,data:XMBT5xX5,iv:kKRA1EQMMURm+Ur3MPE3MZmklsHCWT2anlh8N0/f7YY=,tag:QL7n2r/TK5/jYUMQQjnW8w==,type:str]
stringData:
    token: ENC[AES256_GCM,data:kHWIDGFKNu/4n8RPGtLF09aft7lnihmwNBklVsq+yRh1z8SaiOf8rMDOR5D9LS2O8PAZk6bI6s3o9Gw5F5Ttlw==,iv:kXZz54kh0nqMO0iRPDmBx0kWkdfTTBLn3SBu/hEsy+E=,tag:hdvggJtw9Uk0HgtuWLXbpg==,type:str]
sops:
    age:
        - recipient: age144j6mc8rwf3krfz3u54lf6jsncjwu6dsj423ck3jasq3yhck2f7qvzm9au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZHQ1K1JiRk96SE53R0kw
            bWhXNHB1TVNOSU5FbmxLUU45eXBoT1BDMFRzClJoa3VqR0FjRkhuSmtUYS9wQlhZ
            dTZxbWVkY00yWVBlWXNNYmFmajhPYlkKLS0tIDV4WkdCbGZ0bWo0eEk5cnM4NkRF
            am4vSE9kMmlNU09DREFIaVo3K0pLUFUKHq77JmgiX6d83+EG904E5F89FkM/Cul0
            TZuLQr4lhd/C0WGJfQFw/c+s2/HyLCpl35EyiL6yTA5YAKvQmXjw5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T05:18:33Z"
    mac: ENC[AES256_GCM,data:EOmztfRwyWqIiie9G9NgEtStIjS0INSfU0YtOjAAjFKLyD9icqGGe5Nbf4IHZV3cmEFGOuF6nLwpzNcBhJlZon71r8F/9cEzvmyv+oeb6enCE22Q7/0U+3MT7hi7O9pGX8fJ3SEWQ2tgn3Q3w/VovPYpXgkm1vyehKyUqaKsRNE=,iv:Loq0Aidz8TmrAR2vWrtmt2tX/oiBiLpJaxneetnOx9A=,tag:KQ1WRzp2hOHzd8j6HDBOPA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
