apiVersion: ENC[AES256_GCM,data:40c=,iv:CLHMgafvOeOOBZU1YyB81rUGZrSnsm2pBB5ivOdfC2c=,tag:uDQgIHrrh2fZ1Imtd3z6FQ==,type:str]
data:
    ACCESS_KEY: ENC[AES256_GCM,data:ZAwCJ/tUhEpSLaMuUHU0foCSSFpuGePxieMxrIhEy4W75L8Eqjvyj0zxz4M=,iv:MdNe7oJEUyWpmvuC6uk9wnrJXfNdpSjS3AuDe6a4FXk=,tag:gBMtofmN5fcYjKcy1uojMA==,type:str]
kind: ENC[AES256_GCM,data:cnwEqACY,iv:2J6mJ0Rz/Tq+aUQj2HG2QS5I6lS1LBXl3dr0ZhouyqM=,tag:THsDpeyqcLwSzesmViXKpQ==,type:str]
metadata:
    annotations:
        apiVersion: ENC[AES256_GCM,data:6LQ=,iv:eqG12vvrs/CIBUFbPUzsOQkV5b6KOmGdImp6gauf0mY=,tag:uajMc9iU3cU4k842iJasEA==,type:str]
        kind: ENC[AES256_GCM,data:lVsnE3bF,iv:1a9XQAn9GpGdnuSHBbmA0wkBwfTCxk6DWWTZJyPlmrA=,tag:dPcLUUHrCNoHjdeXG3sAaQ==,type:str]
        metadata:
            annotations: {}
            name: ENC[AES256_GCM,data:EiLeOTwBJmqRWX2CGNt+,iv:IOIDyGSO5mnNQIteVoI4zp4JH4D7cQHnsCk1j1C7qZs=,tag:irctvGj7UZQftdjvnnR8pA==,type:str]
            namespace: ENC[AES256_GCM,data:wB27szwKoB8=,iv:eAGK1GmS//jWMNMN1siitfQqI3mszlMi7LiYETSmxNg=,tag:JTT/vymgcHRGAAc8UbF7WA==,type:str]
        stringData:
            ACCESS_KEY: ENC[AES256_GCM,data:YpT9m+KePGxvpnMGFEX8IYY2I88qlJwm5Ha0rBWHG9s=,iv:NyOD4j/QYayEYEXYH5I3toWiN0vQXS2CoemUWKxlZ9s=,tag:nczxK6Mruz0ntU53JJFn7Q==,type:str]
        type: ENC[AES256_GCM,data:uxz95qj9,iv:EC91UHMz8Ij8Rz5Hmi1gs5c9oij8AHq3C9NXVvkth7A=,tag:bVB3ggOHzDeY4kfmxqmQbQ==,type:str]
    name: ENC[AES256_GCM,data:3J1nLMzAFRplRHdwEC1f,iv:o4uJiXvTyLxigR1fRz5BOe/sGdvYEa3pM/ESqaOGlRc=,tag:npYIB7f+sK66vzSS0xLqRA==,type:str]
    namespace: ENC[AES256_GCM,data:LHqxowkJlO0=,iv:GsUntTC3o6WoDYGOalhAulzb37rY1SNCLH4Dbb0S5OY=,tag:g3r4Hwrn5zpuB5LUEvxwsg==,type:str]
type: ENC[AES256_GCM,data:qMv34Cru,iv:L1qP+FGawgOii4XO9dH5zASEUItDvczvWKE8BHsjScw=,tag:xr0dTldPNBYlH+fLEXfpDg==,type:str]
sops:
    age:
        - recipient: age144j6mc8rwf3krfz3u54lf6jsncjwu6dsj423ck3jasq3yhck2f7qvzm9au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UG1UQktsdkVuMTZMbXFp
            UkNLMnNSbnBvY0RKQzZOOGg5cEtqZEZzK1M4CktQeVpDWENnSUZmMmk5SFdHWDdO
            TVE4Vkl1L2xNaWZHelRRSWQxQzU1bncKLS0tIHhiL3hEb2dkZm10MjB3VG0rYWtj
            MWZIc0pwOTlQRTBMa0Vva28rRDdkdVEK435jCUyKbjhT22+wMCi3S79VUXegzXUo
            pxr6Yw0tAmGouO04eZ9ZZOvWuhS/ztVPpXR0wFr0W+o7RwVz9EnB9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T01:30:45Z"
    mac: ENC[AES256_GCM,data:7hDOOY3e0j8t5x/j6sSWrwPRnxqDbnaUfKFGVZL8DYfv1WTH47WPXClxWkXSqx3Ox/D27e9Buly49cgfYysy7uJKTbqJQSopA64q3F8ZzbdGwGpHk3VxJYL5ZMff8ibPNgARqyfgJj6Vuh9YKalUDXsZUY1t9+P054xB1GEDsgk=,iv:HnGsXy46k7f/jN9K8IBx3kWHE2mVRsPG1Nx9NitXmzM=,tag:XfeD+BDlSgYQl9WF5hwYRQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
