apiVersion: ENC[AES256_GCM,data:0MM=,iv:FO8ZRAR7eMIHBgnqpxKZE0uOVjrPiKRLxz2j0H5v4m4=,tag:02r1DXK3JhzYQy71MuLajQ==,type:str]
data:
    FRESHRSS_DB_HOST: ENC[AES256_GCM,data:+K+lSuslwLH40KqlAZE+mRMXij02d20Qz3LauGubsVd0Ap7UV6FH/OZY9MHQ5T8bqfzNXPWahOEbU3IR,iv:SYGpGqQwXGDLJfwWhrYVqj/X2esCNSbrPgakAex7hrI=,tag:hqW89yfbO4+tnskLtrWVbg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Fv50dc7e1VgIMrQe,iv:sP3CtHeEQ732AvN9J4Q3I6BWcDOJrpJwrKHJNP0lrDM=,tag:WwQLnoWZkbjhdtBW46FnPA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0qlxQMhJtPmCTXtVRe9yoNJrySnBs8/IjAf4wk47WwZ7hmB4AI/UiNh4al0=,iv:gGS9nbHv2nxHLeQM28leGUZX2mYBNd5beb4TsFuJbRE=,tag:u3hoEQponuUFqFMZJl1taA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:M0DV2M4TDc5bTIfJ,iv:c4Nfx6vLFUS8Z47jo3ag4H/3Eyc1YiTimpZXEsX5B+g=,tag:C5+NmFd1B7YUKfl+P+N1Sg==,type:str]
kind: ENC[AES256_GCM,data:y9LR+6pA,iv:+0vD70q+XJ3pmINfHJoecuWLbX9zKV1g3CLMUru+1EM=,tag:xjLTLBwOZLoOQMQCWOR9sA==,type:str]
metadata:
    annotations:
        apiVersion: ENC[AES256_GCM,data:JKg=,iv:0+/AvZnt6+ONxIO8v5ASjidRKA1Y8KaixoCC5jyvYy8=,tag:gDBILMhu4vRJzZLWV7Yb7Q==,type:str]
        kind: ENC[AES256_GCM,data:hi1zpAob,iv:U1D3Ufv1nGjeeuG5h/NJbXRM+uckVGnxzii5WTIcyGc=,tag:A196Judy1bW+I/s6YnkLHw==,type:str]
        metadata:
            annotations: {}
            name: ENC[AES256_GCM,data:BSagJgUtpO8hSsf/avbCF0s=,iv:0NTXvEGZb1jXcz4LyzVT8HuSrC8+9/dAvT6JbTXCdQo=,tag:vE8S3zJdlUednqHaIqiqAw==,type:str]
            namespace: ENC[AES256_GCM,data:iOl/eMrsiX0=,iv:ePFEe4FGgoAodD4IdqEAIH4A9Hbz6uGw7fr/KyqTaBY=,tag:WBsYY9SzOtDyfDScSUsAJw==,type:str]
        stringData:
            FRESHRSS_DB_HOST: ENC[AES256_GCM,data:+sf4E9vLZrskpdYOY48OY2IDpLdrmsFhWbyQChi4yhNfoO6zlZUmkF9a1Qs=,iv:yrwz2Np9rfQG1VvuABu4hdS/i9q6iyuLYJb29cjN5B4=,tag:28fEYaDZKdBSJaIDV5Jyrw==,type:str]
            POSTGRES_DB: ENC[AES256_GCM,data:C09aRLJdy4k=,iv:c+nluTBwoAfTZNSgzR8iCWBkjKf5h0E1LS/UQJ1qz0o=,tag:rkPaf3J2Cle/ShStRRfqSA==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:AX2mAWZxtII1XRIkaIoxrozhPT2ToYYoodDrA75EbfU=,iv:mm1Zq9gIZ4Y69qtKr5oIYtWFh6zNALZTibIEGTFbb4U=,tag:srX8oU3dwDldCjpORRZ6og==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:Shv7S1iAABE=,iv:+/K8TCztLtRCgMtr2n51jfvPWp/yfgsZo1zPZDiAXfI=,tag:0Oct3h5e66kVNFI/ZVdNwg==,type:str]
        type: ENC[AES256_GCM,data:wT/vK5VW,iv:YT8GcUwoM91jm61iOMF/mdzEymE/4bZi+922vwSbbxc=,tag:/rMHJGK946WkhcoRL8ZaTQ==,type:str]
    name: ENC[AES256_GCM,data:+Ovg/NIBGAA8pSkI5jWq03M=,iv:FjaZf/eH3PpOEKuJ4M3F/pD2FuH69BiCmfNhmXsLqUU=,tag:utIGdvDujjAwh+TTeGm8YQ==,type:str]
    namespace: ENC[AES256_GCM,data:X1Vsv+y1mls=,iv:ka56t8aJ4QcKcEhJXXIPlXTrDAKbjnFNJxNlrpShlLM=,tag:b8VWuB0kPEi0gTfGmTz4MA==,type:str]
type: ENC[AES256_GCM,data:HcneC2o+,iv:6na1BUUvP2BcKRS8cK/nsgrIUemcFomH+XEL5hwLfAU=,tag:6M4mD3PLzWOchduTqH1GyA==,type:str]
sops:
    age:
        - recipient: age144j6mc8rwf3krfz3u54lf6jsncjwu6dsj423ck3jasq3yhck2f7qvzm9au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbzArZnlsOXpGa2htc05p
            TFlzNzhtcVp3a3BKZXRrZ2xRSG8rYnJrOXcwCkt0RXllckZtUk4ybGoxU0twcUtx
            dENDdmRreDJnMXpwbU9vbmRMZ1BUNmcKLS0tIEc0RXc2N0pzZkhWVnozN1JNTmVp
            Vmp3S2ZjVmNCKzJIWXB6THBKQmNySk0K9U58kvZVzBtMk2CoyivzLyLBy2IbItM1
            Usj9/5oW8bu3VXLSfn0wfz/tnDy9n90p8to8aeot0n50p+ImfFbz3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T01:30:45Z"
    mac: ENC[AES256_GCM,data:ah0dutpUzjcEY+dBS7aFiKeoJh8LrdROON38QMGGLf2vqFBXFISS1X0mkKaz8kWKnaYKsJU+o1KDKpGJ4hvgWzGZPtF0bSXvXTa4b8A/PLUefPSwvJGudHH49LYIFdABcnODvFW0xbVRmIWJtrUB7LrqesEZVlF1sg1q3BwnKtM=,iv:yD3mmzraXgzbhLfWEzsFXl+RUF+yGwes8ZR6QQc3dHE=,tag:d2B4jaCE1JkYwEycKsADjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
