apiVersion: ENC[AES256_GCM,data:7wA=,iv:Fqs+BS1XgvWh5i56kmJOCwqHMon1VVNfVtWZ/so8XWk=,tag:gFJhsssnkjsRIL85a5rwKg==,type:str]
kind: ENC[AES256_GCM,data:y0pO9tcf,iv:8r13eEWdmhu8MR+6LBtJt8xRruNLVuBiAQ3GCZzWC3o=,tag:sTmiGLVsaeVQLE2pfvWncA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ldO30+9Ey7EeIoVAhAXw,iv:an/tO0wREzjenNLhO2D9R7cQxyjZc7aj6BiMIHnq1UU=,tag:WGqm4++LLwkeNmfXIglfsA==,type:str]
    namespace: ENC[AES256_GCM,data:70yQqrFpVZI=,iv:e0QU35nivxXFJM02f/LODhx6aiGHTXqHS2nifSGtjBo=,tag:Kjw7BJ+7yfsposghWex+Ng==,type:str]
type: ENC[AES256_GCM,data:FvRW5oJX,iv:rKPIX9ooetXdohxvftetqL/5jFu1Yf7T+N69r+z5nCU=,tag:zZK4mLOjY6Oxn2DRRj4YMA==,type:str]
data:
    ACCESS_KEY: ENC[AES256_GCM,data:5AHUHJlgwFPh0Hfg/Y/rvpJ1dPdur++fiKkVNRcejFiFLPv+Kg8sOjxBBGA=,iv:sR87e68utc71LeyKWxBDd3wRUTWCN4j9tgva6obp9rg=,tag:vivMBnL1MQZ6wKUKmMrDfg==,type:str]
sops:
    age:
        - recipient: age144j6mc8rwf3krfz3u54lf6jsncjwu6dsj423ck3jasq3yhck2f7qvzm9au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR0hhQjRDS1puNlVWOGRD
            Y1VuN3JFakU4VmRlWHJ0cUJBRHFYeGNLUm5ZClJib1J5Y25HRkd2MHc2ZitsNzdZ
            K0xhWE1JVk4zVWJCM2oxYmZqdFY3MlEKLS0tIFh3UEp4MjhqbndBSmYwa2wwczdm
            Y2l3MW50cm9YaEhIRlZjVXlLK0tqaDgKSyZRgYbqz9UJYtPEqum1udssc37OaRHP
            Y66oAAyE83b2chAX6aXPVU1ej6agELfd8JvD5IjI3DraQTlsy9xP6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T02:01:29Z"
    mac: ENC[AES256_GCM,data:Ew1fu8GgU2oXMPYxXZFdtah+BQter9LiqkzIR/vfP+v3U0otYb8/TeBHwS+xj9I7ud/aJUMLIhPPdzpVGbs1vnnRC2E+V3fsnur3x5aRYL0Z1s2xWmcPHZiMBZv3TV9xONt3/h7S5Q32jJLrOOUjwJIySeI3muLgwyBJ3lOpVIM=,iv:BNkrptkS2/qAyLPsdxiVxXOO7qtzQOAWYcTuN+X8kco=,tag:NstunE+lfNuWC2iXY8ZjXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
