apiVersion: ENC[AES256_GCM,data:wxM=,iv:WjW9OqKePADOe9ZpbbKjr6k8+a2m7FT51WpWQdvR7ig=,tag:a/ix+I4OOmgMPqYWvuvTxA==,type:str]
kind: ENC[AES256_GCM,data:V66Ezd0h,iv:2PSHu/aZSirujZhq6tkzDvZzlOT7kUdooq5q3Zp7Gqg=,tag:j+BhbY/O3iinZGUQKrDhzQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6xSpez2tDWqkCZS1rA9G/+s=,iv:08nYbKwwtCWLPAnLawbMf2UlK9ctXz0hveFtChjwSLA=,tag:KpG9tXFAHgTKqrHGn4PrRw==,type:str]
    namespace: ENC[AES256_GCM,data:/8Q7ZHmeuIM=,iv:LehFa46WJaGVNX+08Ss9TazU2HlO0+zYpOrQ2EbEQYA=,tag:yUg/TiR6pwidpNN8nlDblg==,type:str]
type: ENC[AES256_GCM,data:sKHt30pO,iv:ucX/BUsbV1xW01K7yIi8sA5rpjSrin6tBcga1WY2UrA=,tag:AREQm3TYq/fzSB9BMAWKoA==,type:str]
data:
    FRESHRSS_DB_HOST: ENC[AES256_GCM,data:czBsF87nQ/lXOK8tkcsRSydTtX1g9JG1SXRmPST+FIgQeOXj1KBdAX/kvdWNX5VLgkr4zEVZeuW1Twm9,iv:lviKfeKWiYi8G3XKK53wqjnTmvAzvZfZIQthm9ViCTg=,tag:AVpSl7ieSzbLCEh6Ip+ChQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:rzxbS4ETtt0B+tqm,iv:SgfmO1MUZgtcHxVBDtdNfXJZa9MBT76WYLSZ9Bkcmvs=,tag:Nsfi/ldj2MF6gG3U1NbicQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5qmrRrVsWK7zQ7+3jTjWhjOFI5jfpEClBcwyawiHrtuUPxrl4uTWo7yrEFE=,iv:q5ZP4K5wBXZ8D4ziVZ74CG8EUXAgOtmUfnJU5/TBdlY=,tag:0/kIX5QGDruIv9m4XJdC4Q==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:qbTpjFoLtMMe1Jb4,iv:F1pZg9d6D5ktBdjBeaQWTTT/M4O45ug/Lj2bL0gxKkg=,tag:7gFviZTnRjIPpGOZoh3rZQ==,type:str]
sops:
    age:
        - recipient: age144j6mc8rwf3krfz3u54lf6jsncjwu6dsj423ck3jasq3yhck2f7qvzm9au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcFk1RTdlMVVDZmxyeC9Q
            WXdUUEh3ZE96aEhzNTB4d0hINXpMeFdnL0FNClRBQUhVdnlDVGlEZDd1WTJ5YWov
            dEhCbVZLdzJnRU9tclJ4OWt0OHVaaUkKLS0tIEE4U2NOckREM3lHR25PQVNFekt6
            ZDRPcmpQODRaSGdsZGtTRTIwV29kUmMK+jFKZMKXALx9AgrlTZUSxb4dTCoc/UDw
            FIqmYRm4CpJT9pP0ggbJ/0bVL3gSeICRg8Gzdo4napK11L6qW9ck+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T02:01:08Z"
    mac: ENC[AES256_GCM,data:HXntPiB5g1UL04v8D/Nlpu5dPUDg7tFGvpGvBsFv3W8W+y4goqRhMy7JFaER7L3UT1MDX25KRIsG94SeFzZPc9M91lm0IEel+FucF0VL9/BwTCuMy5GneeGqdCEgJNdjoWSR1lw/AfcHViwbQPfOypSPeLhvPUbhg/gBuOyYlpU=,iv:ziBvAXMVPUWaX1VAEbxWHJtlwrbQa1LtMZ1/J2Afu7c=,tag:9tAWXGwq0hezvC007IUHLw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
