apiVersion: ENC[AES256_GCM,data:Vrk=,iv:/x6Ynmp8omG+ccnkaJFDO6o6Qx7I438bAR3jQLN6fkU=,tag:P5OBOBl1zdXC3GGmgHMZZQ==,type:str]
kind: ENC[AES256_GCM,data:DPzbDLCQ,iv:jJWGlKe2PHInZvo1+KiLRWdW2xvveZnYZ+VT3FWsjdY=,tag:RLi6w0YqU38Gp/RzXXpOcw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Zr4SQsK7qltk8/+nJdyib1M=,iv:VOK0YnpPEfgisBr+BjlHfY69R2kzgUllcvMTFWRLorg=,tag:e6+bLJ1YI0mXvjQvBKFtsw==,type:str]
    namespace: ENC[AES256_GCM,data:BoNmglLlDaI=,iv:9cdFt8CxWYKO+7nGYtTkGTL5G/29lwNL+B8x3dGd9GI=,tag:A43EPwLA2pM5XaEQ6uF/oA==,type:str]
type: ENC[AES256_GCM,data:YzK8C9O/,iv:fDU0DPFL50mztJGNqelS9qGtkxPm/0ojtMIZaggtG6U=,tag:t55+8rRQoN3qo+3f4qPR3w==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:NA57sCdeE78=,iv:RCX6kLpkEJQC0P3QxTxRJ4HnDwwljtK3Bz/5f7VuQDE=,tag:U82JNUhT+g44qWNjzPwZaw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:mne+DRwqfq8=,iv:y7FAd8n6MVai/BjFnHbwVctJ168Krm26ZLtC0vzHNyk=,tag:3ZIBruO4PItSRw03iMKHyg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3gdiwi0w/kkElW7TY4mRj9U9/DA6xTWrmh7IBa7kfSY=,iv:XlJM4luwlfkYvUAc+yBy9VJ1jMgba/41Skp62xLqGyY=,tag:lta+lPoV8zQAzMUMBZ+Hnw==,type:str]
    FRESHRSS_DB_HOST: ENC[AES256_GCM,data:OKsJA0r9S+Nit2F5vzy8sbpkpLA7wivd8Rzj4GGOn2AXotaLHCEwfJrCjso=,iv:xRf9MeNwJnfQp2PiLvBXJiiUUB6ioABbetMHZYPU01c=,tag:HRgeeCEt4agMCRG/3RqYrw==,type:str]
sops:
    age:
        - recipient: age144j6mc8rwf3krfz3u54lf6jsncjwu6dsj423ck3jasq3yhck2f7qvzm9au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMjgxempxOTNwMW5EVTRE
            WnZ0WTNVRkRQSzd4Z3hOSmlORHVWVDNVNXpZCnlkN0VsazgzK1RXQ21zcUlpL3h5
            eXE1a1NQWHB6QlNhYzA3RWNrcUYzbW8KLS0tIEpDbnRPRTBDZkh3R1dSZ3dFc1Qz
            TkpkOHFlSkppOWtzY1dNSXhMbVBjZk0KNj/AxVRQ6CaUGk5LoOufb7laqu4r/jY0
            NllOIBqyJTL7UULI620KsmdABgcs5OuOtNjkciQzw4TjnhpX8svrGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T04:01:57Z"
    mac: ENC[AES256_GCM,data:5s+59yGIiPXtdr3dHWsWNewod21Evsnvv9APLiSTcmOEBAud17v+LEU2T8UUqgGElCTeyDC7hTRbd5CpH+tG850VSd/s9h+KDoq47VDu0piAZbeEphK7wItxJXjwzRKLfx7mAHqshm8UCnOpyxNPBkdNP8HyxCcjoeiXzY6CUOI=,iv:/o5FRMuQB4mGflOAhm1sW9WTg3cKc85GqosMS9cQEww=,tag:YnxIah8aehvYRz2yWoFktQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
