apiVersion: ENC[AES256_GCM,data:mVU=,iv:xQAVNm62CfsQ8uuEthKJtAWVfLazcYqqsO9Ll8XLDKs=,tag:7VtlVpzYF00RH0HFIatxGA==,type:str]
kind: ENC[AES256_GCM,data:Ndkw98VT,iv:OY9LQ3DUYezlLV714bSduN5skb0H4i3aXt05SBLLMpc=,tag:MktzhopxxooCGYWlARctUQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jYTIWT61VNXCn2PkoeId,iv:V/0stsZHPm4LsIK8l3z0bfwGKIPA+6wCInEbECTFv2A=,tag:bqmYguy6IIn+19bzYFpsZQ==,type:str]
    namespace: ENC[AES256_GCM,data:39xoAv6c3BM=,iv:zJPeTtJfejxPLi+pQ92bmNyzzvwPAAzpi+9x8Bvt6ec=,tag:KjHwo/xBB9X4ouTZgmsDMg==,type:str]
type: ENC[AES256_GCM,data:FcyZfCNG,iv:BF8/krzSiWQf1G6SybEF6QfTGQbpxwed5azyE+lnd9Y=,tag:kaAM2KCltG/hfw0jjFvH8Q==,type:str]
stringData:
    ACCESS_KEY: ENC[AES256_GCM,data:elFAp/O4w5v1CCE5GjyvAx5emozYNWLIHL1V5pvlgXU=,iv:24TsH+iBconqVcKyUZK25zCSrwWk4sqmzEZumH/cys4=,tag:WB7tHV30jDSMc7dzJ+YFBA==,type:str]
sops:
    age:
        - recipient: age144j6mc8rwf3krfz3u54lf6jsncjwu6dsj423ck3jasq3yhck2f7qvzm9au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQndCdDlSS2hoYXd4OUp4
            NWp4MEIzYjBma0JtNDBzblJKNHJYVDVFRlZBCk9zbVVZeU55cUxXUmdicW9rZWpD
            eFVtMmsyUFdqbnNUa0JCNGhyc3dSYWMKLS0tIEQrOU96MGRjMFVudlhScHVUQnFM
            ZUluS2Q1RkpuN2JtbzNkQjhuaTdad0kK4VzgTxpsG2c0JIv7M6rTVqSRhlt3VaSf
            a90mCOeV2P5x4b3tZpTG41T5ePG+863Bby7c0ncPvvB+USYnvjSC9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T04:01:57Z"
    mac: ENC[AES256_GCM,data:9M/bIoUwjTTS7/CFn7zAIAoB974IIZyZ7Nias/QJKpqdvz7Fuvg2vhLkQUzl6jZhMdT57gSerp6saLCd6UswiNUJT8tRYR3qf2641UIHqc0sEE3a0S60lZ3H2Evro+tuHh4NRxpAzIIf2hCEO69f1pukzpJ+nFjcbPlO9kx9Pdg=,iv:rJtnVfHLi0xBfakCAK6NgC1PfVGryVjq2ZWIkIetW18=,tag:W5QsKngL8MARakgJuDGQ6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
