apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.freshrss.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.freshrss.persistence.size }}
