apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freshrss-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
    {{- include "postgres.selectorLabels" . | nindent 4 }}
spec:
  serviceName: freshrss-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          envFrom:
            - secretRef:
                name: freshrss-postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.postgres.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
