prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    retention: 15d
  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.10.61

alertmanager:
  service:
    type: LoadBalancer

grafana:
  adminPassword: "changeme-grafana"
  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.10.62
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 5Gi

kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
