apiVersion: ENC[AES256_GCM,data:1+8=,iv:lG0LG9xIoBXgQ5Vetl/i9iNaK9FpKkkS+vJx9uzzZdU=,tag:23jK42t0+p1QFu6Fj5+o8A==,type:str]
kind: ENC[AES256_GCM,data:gUthwwRR,iv:aeYCboyrSJIqqYLFLmh31WYrAhkTwe6KYOffovhTrlQ=,tag:IUPYO5pt47QPY4FT9cKLgA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:brzuo429wXS6UCw=,iv:KZ13nHyNUkMVwv/jUM/i9VMFUoM/7PyUiZpCi/zeAik=,tag:z406GoQxYbZJM80VwLxnRA==,type:str]
    namespace: ENC[AES256_GCM,data:MIXDZHIg3Q==,iv:qBNxzuZ7EpyFBkgyldqf9q3mrgraOVYj9uOYj5oErWY=,tag:vOssQLFquXoo1uz9Zj7T2A==,type:str]
type: ENC[AES256_GCM,data:vONp+cOq,iv:KbDOrQJHMDKr1VGBlWss8al5Cq6jIflUW5/1u+1Zzl4=,tag:E3xapcL6KzrxJwVddGFwuQ==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:3NGlvW7rO3kvCozBA8k5tINabmei6lmB,iv:zCNVCAw3kfoKs2PTcNAq80yGDODDbFP4lHuJefPTVp0=,tag:BuLRcIfJGpsHL2mh/ZRt/Q==,type:str]
    password: ENC[AES256_GCM,data:NtFuLNoX4iHAUN7qH7xm0dYAgWJx,iv:1vNSq5MfDRRZFwhpa8RVtEhEWZdAyzhoUfQmp/tAGl4=,tag:glJqfDS3cAx8x4EQDNuvVQ==,type:str]
sops:
    age:
        - recipient: age144j6mc8rwf3krfz3u54lf6jsncjwu6dsj423ck3jasq3yhck2f7qvzm9au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VXpJKzRiaklmTVl2YjM2
            cC9CTTcvV3lDNEcvZ3dWdFJxWEwvN2M1cFM0ClN4RGVoZmRWZEtiZmRZUU5BWVAv
            YjkzdURKeU9zT0d5cmZpMklqK0VEZXcKLS0tIFN6RllxSis2N0VodHFvZGN0Y0Vv
            TWRvSWZYTS9FY0o0L2xmWm5Nc21aYm8KH12dpis+VUN4eloAc5KYrnTpKAHkO5l4
            NkdvO9bcdcCkv8QEpQfGodnOmveYZKRaPhH7Ko1lnZWH9vw4kZ0BmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T01:50:17Z"
    mac: ENC[AES256_GCM,data:IG413eqxkGRjPmIbS6RpXhrRWoKbYWKrWbo07V16ah6T3Eeb5Hw3HMQcpjgHUA67W7QvpVI+NsPNuD4hSvPtFYiNwAHEAheOriFslyMVYE6bja9mQbImu/YmDZazAq+Gc+6gL1D+yZGtcqvofYjcmNT08Akrw/Lp0EPB3Y9EsYs=,iv:KcBwIAb+U5lXY9nhq+/1bOWTgnaydRZhbVj/xgl1LkE=,tag:8YvuFMysWAUcN0OUl7f/eA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
